<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbladmin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbladmin_model');
    } 

    /*
     * Listing of tbladmin
     */
    function index()
    {
        $data['tbladmin'] = $this->Tbladmin_model->get_all_tbladmin();
        
        $data['_view'] = 'tbladmin/index';
        $this->load->view('index',$data);
    }

    /*
     * Adding a new tbladmin
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'uname' => $this->input->post('uname'),
				'pword' => $this->input->post('pword'),
            );
            
            $tbladmin_id = $this->Tbladmin_model->add_tbladmin($params);
            redirect('tbladmin/index');
        }
        else
        {            
            $data['_view'] = 'tbladmin/add';
            $this->load->view('add',$data);
        }
    }  

    /*
     * Editing a tbladmin
     */
    function edit($id)
    {   
        // check if the tbladmin exists before trying to edit it
        $data['tbladmin'] = $this->Tbladmin_model->get_tbladmin($id);
        
        if(isset($data['tbladmin']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'uname' => $this->input->post('uname'),
					'pword' => $this->input->post('pword'),
                );

                $this->Tbladmin_model->update_tbladmin($id,$params);            
                redirect('tbladmin/index');
            }
            else
            {
                $data['_view'] = 'tbladmin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbladmin you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbladmin
     */
    function remove($id)
    {
        $tbladmin = $this->Tbladmin_model->get_tbladmin($id);

        // check if the tbladmin exists before trying to delete it
        if(isset($tbladmin['id']))
        {
            $this->Tbladmin_model->delete_tbladmin($id);
            redirect('tbladmin/index');
        }
        else
            show_error('The tbladmin you are trying to delete does not exist.');
    }
    
}
