<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbladmin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbladmin by id
     */
    function get_tbladmin($id)
    {
        return $this->db->get_where('tbladmin',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tbladmin
     */
    function get_all_tbladmin()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tbladmin')->result_array();
    }
        
    /*
     * function to add new tbladmin
     */
    function add_tbladmin($params)
    {
        $this->db->insert('tbladmin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbladmin
     */
    function update_tbladmin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tbladmin',$params);
    }
    
    /*
     * function to delete tbladmin
     */
    function delete_tbladmin($id)
    {
        return $this->db->delete('tbladmin',array('id'=>$id));
    }
}
